- src/main/java/net/ausiasmarch/wildcart/bean/TipoUsuarioEntity.java
TipoUsuarioEntity created by Josevi and Mark.
> tipousuarioentity implemented(josevi, mark)

- src/main/java/net/ausiasmarch/wildcart/FacturaEntity.java
> Creación de FacturaEntity

- src/main/java/net/ausiasmarch/wildcart/bean/tipoproductoEntity.java
Creación Entity TipoProducto Por Hector y Jose
> Entity Jose Hector

- src/main/java/net/ausiasmarch/wildcart/bean/UsuarioEntity.java
Entity de Usuario
Pere, Jose Primo, Daniel
> Creación de UsuarioEntity

- src/main/java/net/ausiasmarch/wildcart/entity/ProductoEntity.java
> Crear ProductoEntity

- src/main/java/net/ausiasmarch/wildcart/entity/FacturaEntity.java
- src/main/java/net/ausiasmarch/wildcart/entity/UsuarioEntity.java
> Sergio-Aaron usuario-factura

- src/main/java/net/ausiasmarch/wildcart/repository/CompraRepository.java
> Creado CompraRepository

- src/main/java/net/ausiasmarch/wildcart/entity/CompraEntity.java
- src/main/java/net/ausiasmarch/wildcart/entity/ProductoEntity.java
- src/main/java/net/ausiasmarch/wildcart/repository/TipoProductoRepository.java
> Creacion TipoProductoRepository y relaciones de compra y producto

- src/main/java/net/ausiasmarch/wildcart/entity/CarritoEntity.java
- src/main/java/net/ausiasmarch/wildcart/entity/ProductoEntity.java
- src/main/java/net/ausiasmarch/wildcart/repository/ProductoRepository.java
Created Producto entity and relation between producto and carrito.
> Jose y Mark

- src/main/java/net/ausiasmarch/wildcart/api/SessionController.java
- src/main/java/net/ausiasmarch/wildcart/api/TipoUsuarioController.java
- src/main/java/net/ausiasmarch/wildcart/bean/UsuarioBean.java
- src/main/java/net/ausiasmarch/wildcart/entity/TipoUsuarioEntity.java
- src/main/java/net/ausiasmarch/wildcart/helper/TipoUsuario.java
- src/main/resources/application.properties
Create UserType api and UserType class who contains the id of user type, this java class works like a JAVA ENUM.
> User type API created

- src/main/java/net/ausiasmarch/wildcart/api/ProductoController.java
> ProductoController

- src/main/java/net/ausiasmarch/wildcart/api/TestController.java
- src/main/resources/application.properties
Made by Mark Coronado Cabanes and Jose Peña Tatay.
> Create a TestController to manage every Test Services.

- src/main/java/net/ausiasmarch/wildcart/api/TipoUsuarioController.java
- src/main/java/net/ausiasmarch/wildcart/api/UsuarioController.java
The error was that when we made the purchase of if it was admin, we only checked the user id, not the userEntity.getTypeUser().getId().
Sorry so much for the error.
> Fix bug in TipoUsuarioController and UsuarioController

- src/main/java/net/ausiasmarch/wildcart/api/CarritoController.java
- src/main/java/net/ausiasmarch/wildcart/api/TipoUsuarioController.java
- src/main/java/net/ausiasmarch/wildcart/repository/CarritoRepository.java
- src/main/java/net/ausiasmarch/wildcart/repository/TipoUsuarioRepository.java
- src/main/java/net/ausiasmarch/wildcart/repository/UsuarioRepository.java
Made by Jose Peña Tatay and Mark Coronado Cabanes
> Standarize Carrito filter and TipoUsuario filter.

- src/main/java/net/ausiasmarch/wildcart/api/CarritoController.java
Hemos añadido todas las funcionalidades para el CRUD
> CarritoController adapted for crud

- src/main/java/net/ausiasmarch/wildcart/api/UsuarioController.java
By Jose F, Hector, Jose P and Mark
> Fix bug in User Controller

- docs/sessionAPI.html
José David Rosales y Carlos Lazaro
> Sessions Upgrade

- docs/productoAPI.html
> productoAPI.html (Estefania Boriko Laenos y Alvaro Talaya Romance)

- docs/productoAPI.html
Añadidos botones y justificado texto.
> productoAPI.html (Estefania y Alvaro)

- docs/tipousuarioAPI.html
Cambios en las request de postman bien realizadas , getPage si que puede ser accedido por usuario(2) , esto es un error?? 
El generate y update si filtro solo admin.
> Mario/Jose Cambios peticiones mejora spec API

- docs/carritoAPI.html
> fix: order of operations and url path variables
